### ISSUE TITLE
Volume Enhancement and Unkillable Last Mob Bug

### ISSUE THREAD

**Issue by eeng20** [cis3296s24/Second_Chance#45]
I read the project's README and followed those instructions. I installed and played the game on a Windows PC (very easy installation and setup). Something that went wrong was when I lowered the volume on the main menu, it works but when I go into the game it resets the volume, not sure if that's intentional. It's really loud on start-up but I think that's any other video game out there and just depends on the user. I also can't access Options in the game either because I was hoping to adjust the volume from there. Not sure if this was intentional either but I can't kill the skeleton? It keeps running away from me but other than that it is pretty neat! Can't wait for more updates!

**Comment by VictorTran259** [comment]
Thanks for the feedback. The bugs with the options menu not being able to be accessed in the pause menu in the game, the skeleton being unable to be killed, and the volume being reset when going into the game have all been fixed.
