### ISSUE TITLE
Cannot touch or attack the soldier enemy

### ISSUE THREAD

**Issue by tun08131** [cis3296s24/Second_Chance#46]
I was able to run the application fine on Mac m2, but there is an issue where I cannot approach the soldier enemy, and also there is a big block where I can walk through it, and when I jump I teleport to the top of the block.

**Comment by VictorTran259** [comment]
Thanks for the feedback. We have fixed both bugs that you mentioned with the soldier enemy being unable to be killed and also the bug with the big block that you could walk through and would also teleport you to the top when you jumped.
