### ISSUE TITLE
Cannot kill second enemy and option feature!

### ISSUE THREAD

**Issue by tuh25772** [cis3296s24/Second_Chance#48]
I have a Mac 1 laptop. The instructions were very clear and I had no issue running the application on my device. I was able to clone and run it straight from terminal.
The sound was increasing/decreasing properly but the number next to "Volume" always remained at 50.
When I started the game, I was able to use the necessary keys to make movements and to attack. However, after the first kill of the one of the enemies, there was a certain point where I could no longer move forward.
Even before that, it was nearly impossible to attack/kill the second enemy.
I also noticed that I am still able to go through the brown blocks. I assumed I would be stopped and would have to find a way to go over them but I was able to run right through it.
One last thing was that when the game starts and you pause it, the "Options" menu, when clicked, doesn't display anything. But I understand, as this hasn't been implemented yet. But it was just something that I noticed.

Besides those, I think this group did really well!

**Comment by VictorTran259** [comment]
Thanks for the feedback. The bugs with the volume value always remaining at 50, being unable to move forward after a certain point, the skeleton enemy being unable to be killed, and the collision for the brown blocks has been fixed. The options menu in the pause menu has now been implemented as well.
