### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by MatthewChristofas** [cis3296s24/Second_Chance#52]
On a Macbook Air M1, was unable to install the requirements txt without creating a python virtual environment. After creating the virtual environment, I had no problem installing the dependencies and running the game. I was able to create a name and play the game, I was able to kill both enemies and complete the level. I noticed that with the large tower like platforms that are supposed to stop me, I was able to jump while inside of them and it would shoot me right to the top. Some of the platforms act similarly to this. Also, after letting myself die, I tested the minigame. I noticed that there was no wrong input, so if the letter was z for example, and I clicked any other letter than z it wouldn't cause me to lose. Also, after spawning back in, I could continue to die as many times as I wanted and play the same minigame over and over. The volume control in the options menu seems to work, but the displayed volume level doesn't reflect the changes

**Comment by VictorTran259** [comment]
Thanks for the feedback. The bugs with the collision of the tower platforms, the reaction time minigame accepting the wrong input, and the display for the volume control have all been fixed. We have also added more minigames, so you won't have to play the same one over and over again now.
