### ISSUE TITLE
Jumping on top of terrain when it shouldn't

### ISSUE THREAD

**Issue by tun51789** [cis3296s24/Second_Chance#68]
When playing the game, there are some cases where the character shouldn't be able to jump over a terrain but the code pushes it to the top of the terrain. Either by staying on the side or have a platform above the character and it being "sucked up" to the top

![image](https://github.com/cis3296s24/Second_Chance/assets/143668310/0e043a86-74cd-4055-9c2a-dc978886dea1)

**Comment by VictorTran259** [comment]
Thanks for the feedback. The bug with the collision of the terrain has been fixed.
